# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Grand Tech Tutorial Buffet
email: sciencescribe [you know what symbol] outlook [dot] com
description: > # this means to ignore newlines until "baseurl:"
 Munching and crunching my way through the internet's grand tutorial buffet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ScienceScribe
github_username: ScienceScribe

# Build settings
markdown: kramdown
